// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sesklvvqgfigmyuornph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlc2tsdnZxZ2ZpZ215dW9ybnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzgxODQsImV4cCI6MjA3MDY1NDE4NH0.LpnXOeYpwDiAuI2qSVOpS9--oNiyRJTUXpTTt_HGAP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});